### ISSUE TITLE
Support for Lex V2

### ISSUE THREAD

**Issue by SharvariNagesh** [codeforequity-at/botium-connector-lex#11]
We are not able to connect to LEX V2 using this connector. Wanted to check if this connector supports LEX V2 and how to configure botium.json for LEX V2

**Comment by codeforequity-at** [comment]
Currently not supported, only V1. Added it to our backlog though, seems to be worth the effort.

**Comment by MonkeyOfRoll** [comment]
Is V2 now supported, now that BOT-2556 is there? I am having some issues connecting to my V2 test bot, and want to confirm this is supported before proceding any further - thanks.

**Comment by codeforequity-at** [comment]
Yes it is.
